# Generated by Django 3.2.2 on 2021-05-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField()),
                ('altitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('speed', models.CharField(max_length=100, null=True)),
                ('ENGINE_RPM', models.CharField(max_length=100, null=True)),
                ('ENGINE_LOAD', models.CharField(max_length=100, null=True)),
                ('AmbientAirTemp', models.CharField(max_length=100, null=True)),
                ('ThrottlePos', models.CharField(max_length=100, null=True)),
                ('insFuel', models.CharField(max_length=100, null=True)),
                ('valX', models.FloatField(null=True)),
                ('valY', models.FloatField(null=True)),
                ('valZ', models.FloatField(null=True)),
                ('zone', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'unique_together': {('cin', 'time')},
            },
        ),


    ]
