# Generated by Django 3.2.2 on 2021-05-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_averagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagedata',
            name='road_length',
            field=models.FloatField(null=True),
        ),
    ]
