# Generated by Django 3.2.2 on 2021-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_averagedatapersegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagedatapersegment',
            name='distance_between_end_node_and_point',
        ),
        migrations.RemoveField(
            model_name='averagedatapersegment',
            name='road_length',
        ),
        migrations.AddField(
            model_name='averagedatapersegment',
            name='counted_value',
            field=models.FloatField(null=True),
        ),
    ]
